services:
  wb2api:
    container_name: workbuddy2api
    image: "ghcr.io/xigemax/workbuddy2api-panel:latest"
    command: ["-config", "/app/config/config.json"]
    volumes:
      - ./auths:/app/auths
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "7863:7863"
    user: "0:0"
    environment:
      TZ: Asia/Shanghai
